name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyterlab=4.0.5
  - seaborn=0.12.2
  - pandas=2.0.3
  - pip=23.2.1
  - pyarrow=12.0.1
  - pip:
      - wandb==0.12.17
      - ydata-profiling