name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=2.0.3
  - pip=23.2.1
  - mlflow=2.6.0
  - scikit-learn=0.24.1
  - matplotlib=3.2.2
  - pillow=8.1.2
  - pip:
      - wandb==0.12.17
